Navigation feature
micheaol/Awesome-books pull request #6
Opened 2021-10-21 22:55 UTC by micheaol

In this pull request we add: 
1. A Navigation bar.
2.  when a user clicks on any of the links, the main area changes to display only one of the three content sections.
3. Display the current date below the navigation bar
4. Add three content sections:
     - Books list.
     - Add book form.
     - Contact info.
 Please note that all linter was passed when ran on the system including the webhint screenshot included below:

![webhint-error](https://user-images.githubusercontent.com/10332499/138367837-8b047564-a957-4340-bd02-76a715078c04.PNG)

2021-10-21 23:47 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello @micheaol  and @eapenzacharias, great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️
See my inline comment to know what changes are needed. 👇 👀 

- [x] Kindly add the steps on the Readme file to run the project. Currently, there are no steps.
- [x] Please add the Live demo to your Readme file or delete the title that said `Live demo` 
- [x] Please add `.eslintrc.json`, `.hintrc` and `.stylelintrc` to .gitignore because these files are to test linters locally and are not necessary to run the project. 
- [x] For the Error you got with the linters. I got the same error locally. Kindly try to fix it if it doesn't work it should be an error with the Webhint so leave it like this.

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![cat](https://user-images.githubusercontent.com/64173189/131593916-14c184cb-b5af-40f7-8fba-779155f154cb.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-22 08:53 UTC, DeliceLydia requested changes
## Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-22 08:53 UTC, DeliceLydia commented on README.md
- [ ] As the previous reviewer requested you should add how to get the app up and running locally
step by step so that even a non-technical person can understand
- [ ] Having a live demo is good kindly add that

2021-10-22 09:17 UTC, micheaol commented on README.md
Hi Lydia,
Thank you for the feedback. 
I think all these should be optional as they are not part of the requirement.
I don't think these should stop the approval of the PR

2021-10-22 10:06 UTC, DeliceLydia commented on README.md
Hello @micheaol,
If the first reviewer asked something I am supposed to be
consistent though things he asked are easy to fix
and it is always good to accept feedback to be able
to grow.

Sorry for the inconvenience!

2021-10-22 10:07 UTC, DeliceLydia approved these changes
# Congratulations🎉🎉

## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-22 10:09 UTC, micheaol commented on README.md
You are right @DeliceLydia,
But taking into consideration the number of code reviews, I think optional should not block the approval of a PR.

Once again, Thank you.

2021-10-22 10:12 UTC, merged

2021-10-22 14:18 UTC, eapenzacharias commented on scripts/main.js
> +      break;
You can create a separate function to assign these properties so that you don't have to repeat the code

2021-10-22 14:40 UTC, IbrohimRasulov commented on scripts/main.js
> +      bookParent.style.display = 'flex';
Great job Eapen and Michael. I have some recommendations:
* You can use <classList = ''>  or <classList.add('')> and add all styles inside it, so your can minimize your code